import streamlit as st
import time
import pickle

c = st.text_area("Enter your text: ")

if c:
    st.write(c)
    clf_svm = pickle.load(open('clf.pkl', 'rb'))
    tfidf = pickle.load(open('tfidf.pkl', 'rb'))
    text = tfidf.transform([c])
    result = clf_svm.predict(text)
    if result:
        st.markdown("<h3>Your text is generated by AI</h3>", unsafe_allow_html=True)
    else:
        st.markdown("<h3>Your text is generated by Human</h3>", unsafe_allow_html=True)
